version: '3.9'

services:
  db:  # Defines the PostgreSQL database service.
    image: postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    environment:  # Environment variables for PostgreSQL configuration. Reads credentials from .env file.
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=n8n
    volumes:  # Persistent storage for the database.
      - n8n_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:  # Defines the n8n application service.
    image: n8nio/n8n:latest
    container_name: n8n-app
    ports:
      - "5678:5678"
    environment:  # Environment variables for n8n configuration. Reads database and auth settings from .env.
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      #- WEBHOOK_URL=https://fd343c29a6be.ngrok-free.app
    volumes:  # Persistent storage for n8n data.
      - n8n_data:/home/node/.n8n
    depends_on:  # Specifies that n8n depends on the database service.
      - db
    restart: unless-stopped  # Restart policy.

volumes:  # Defines named volumes for persistent storage.
  n8n_data:  # n8n data volume.
  n8n_db_data:  # PostgreSQL data volume.